### DISCUSSION TITLE
Unable to generate Tests file

### DISCUSSION THREAD

**Discussion by nitishpant-mb** [keploy/keploy#1834] [General]
I am using Mac M1.
Trying to generate tests cases for a nestjs project. But Unable to create tests. Need help in geerating tests and locating them.

Explaination
Using docker compose command to run keploy 
```
keploy record -c "docker compose up" --containerName "testkep2"
``` 

This is my docker-compose file : 
```
version: "3.8"
services:
    nestjs-app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=staging
        ports:
            - "8080:80"
        volumes:
            - /Users/nitish.pant/Documents/code/mediBuddy/events-manager/logs:/var/app/current/logs
        networks:
            - keploy-network
            - backend
networks:
    keploy-network:
        external: true
    backend:
        external: true

``` 

After I do this, the keploy-logs.txt file is generated.

🐰 Keploy: 2024-04-18T07:14:30Z 	[34mINFO[0m	config file not found; proceeding with flags only
🐰 Keploy: 2024-04-18T07:14:30Z 	[34mINFO[0m	detected that Keploy is running in a docker container
🐰 Keploy: 2024-04-18T07:14:30Z 	[33mWARN[0m	buildDelay is set to 30s, incase your docker container takes more time to build use --buildDelay to set custom delay
🐰 Keploy: 2024-04-18T07:14:30Z 	[34mINFO[0m	Example usage: keploy record -c "docker-compose up --build" --buildDelay 35s
🐰 Keploy: 2024-04-18T07:14:30Z 	[34mINFO[0m	GitHub Actions workflow file generated successfully	{"path": "/githubactions/keploy.yml"}
🐰 Keploy: 2024-04-18T07:14:30Z 	[34mINFO[0m	keploy requires docker compose containers to be run with external network
🐰 Keploy: 2024-04-18T07:14:30Z 	[34mINFO[0m	Created new docker-compose for keploy internal use	{"path": "docker-compose-tmp.yaml"}
🐰 Keploy: 2024-04-18T07:14:30Z 	[34mINFO[0m	trying to inject network:keploy-network to the keploy container
🐰 Keploy: 2024-04-18T07:14:30Z 	[34mINFO[0m	Successfully injected network to the keploy container	{"Keploy container": "keploy-v2", "appNetwork": "keploy-network"}
🐰 Keploy: 2024-04-18T07:14:31Z 	[34mINFO[0m	keploy initialized and probes added to the kernel.
🐰 Keploy: 2024-04-18T07:14:31Z 	[34mINFO[0m	Keploy has taken control of the DNS resolution mechanism, your application may misbehave if you have provided wrong domain name in your application code.
🐰 Keploy: 2024-04-18T07:14:31Z 	[34mINFO[0m	Proxy started at port:16789
🐰 Keploy: 2024-04-18T07:14:31Z 	[34mINFO[0m	starting TCP DNS server at addr :26789
🐰 Keploy: 2024-04-18T07:14:31Z 	[34mINFO[0m	starting UDP DNS server at addr :26789

I tried hitting the web server with Postman, hit 2-3 APIs, but no tests got created.

Now when I do 
```
keploy test -c "docker compose up" --containerName "testkep2"
``` 
I am getting error 
```

ERROR	No test-sets found. Please record testcases using keploy record command
``` 

What am I doing wrong here? how to get the tests file?
