### ISSUE TITLE
[bug]: keploy is having trouble mounting a file in a directory, in docker.

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#1049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm using ELK framework with Postgres in GoLang. It's a log monitoring application. Normally, the app is working fine without the keploy.

<img width="954" alt="Screenshot 2023-10-30 at 1 52 22 PM" src="https://github.com/keploy/keploy/assets/53110238/24d3eeb8-c55b-48fc-9a1a-df3b86058e0e">

### Steps to reproduce

This is my docker-compose.yml
```yml
version: "3.9"

services:
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: postgres
    hostname: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - keploy-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: letterpressApp
    hostname: api
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - keploy-network

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.10.4'
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - keploy-network
  logstash:
    build:
     context: logstash
    container_name: logstash
    env_file: .env
    volumes:
      - ./logstash/pipelines/:/usr/share/logstash/pipeline/
      - ./logstash/queries/:/usr/share/logstash/config/queries/
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
    depends_on:
      - postgres
      - elasticsearch
    networks:
      - keploy-network
  kibana:
    image: 'docker.elastic.co/kibana/kibana:8.10.4'
    ports:
     - "5601:5601"
    container_name: kibana
    hostname: kibana
    environment:
     - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    depends_on:
     - elasticsearch
    networks:
      - keploy-network

volumes:
  pgdata:
    driver: local
  esdata:
    driver: local
networks:
  keploy-network:
    external: true
```

This is my application codebase :- https://github.com/Sonichigo/letterpress
I'm using `keploy record -c "docker-compose up --build" --containerName "letterpressApp`.

This the Keploy [logs](https://github.com/keploy/keploy/files/13202771/log.txt) in debug mode.

### Environment

None

### Version

Cloud

### Repository

keploy
