### ISSUE TITLE
Add CITATION.cff 

### ISSUE THREAD

**Issue by nehagup** [keploy/keploy#116]
### What do you want to add to the docs? (please state reasons if any)

The standard CITATION format is the [Citation File Format](https://citation-file-format.github.io/), proposed by GitHub:

`CITATION.cff ` files are plain text files with human- and machine-readable citation information for software (and datasets). Code developers can include them in their repositories to let others know how to correctly cite their software.

example : 

```yaml
cff-version: 1.2.0
title: Beautify GitHub sample repository
message: If you really want to cite this repository, here's how you should cite it.
type: software
authors:
  - given-names: Nicolas
    family-names: Fränkel
repository-code: 'https://github.com/ajavageek/beautifygithub'
license: Unlicense
```

### Where is this stated?

The CITATION file allows you to answer the following questions:

What is the name of the software?
What label should I use to uniquely identify the version of the software I have used?
What is the appropriate set of people that should be cited as authors?
