### ISSUE TITLE
[docs]: Unable to run the go lang mux app in the documentation

### ISSUE THREAD

**Issue by priyankkumar218** [keploy/keploy#1193]
### What do you want to add to the docs? (please state reasons if any)

<img width="1280" alt="Screenshot 2023-12-12 204139" src="https://github.com/keploy/keploy/assets/12366834/ae04020c-a6c5-4357-9def-18eaba024c01">

When I initially spin up my container , an error is thrown saying that the .sql file mentioned in the docker-compose.yml is not a file but instead a directory and hence the application exits without running 

And again, when I try to run the `keploy record -c "docker compose up" --containerName "muxSqlApp"` the command waits for the `muxSqlApp` to scale up but it isn't able to do so.

System: Windows 11 WSL 2 (Ubuntu)

I have followed the exact steps as mentioned in the doc but not able to successfully reproduce the results.

Doc: https://keploy.io/docs/quickstart/samples-mux/

Awaiting a resolution on this.

### Where is this stated?

Some issues might be there for the Windows WSL in the steps mentioned, and hence it needs a check

### Repository

samples-go

**Comment by Sonichigo** [comment]
Thank @priyankkumar218 for reporting the issue! There is a piece of information missing in the docker-compose.yml. can you add the following to the docker compose yml at the line 3 before postgres and check once ?

```yml
  go-app:
    build:
      context: .
    container_name: muxSqlApp
    ports:
      - "8010:8010"
    depends_on:
      - postgres
    networks:
      - keploy-network 
```
