### ISSUE TITLE
[feature]: generate GitHub Actions automatically when keploy runs

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1421]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

It would be nice to generate a simple gihtub actions file when keploy runs for the user. 

### Why should this be worked on?

1. Make it zero effort for the user to add keploy to GitHub Actions. 
2. People who imported GitHub Actions into their project will show up on keploy GitHub. 

### Repository

keploy

**Comment by Akash-Singh04** [comment]
Hey , @slayerjain is this issue still open? if so, can you assign it to me. I would love to learn more about github actions while implementing this!

**Comment by slayerjain** [comment]
@Akash-Singh04 the issue is open to everyone. We will merge the first good PR

**Comment by Prasang023** [comment]
Hi, @slayerjain, I haven't done that before for my application so I'll need a little help with this. As much as I understand, for this task I'll have to write a generic script for some user application. To add keploy tests in github actions, is this the workflow: deploy and run the user app,  checkout to keploy and run the tests. I've a doubt like in order to test using keploy, recorded tests should be present in the keploy folder right? how do we take care of that. It would be great if you could provide a reference project/sample app in which github action for keploy tests workflow has already been implemented. Thanks.

**Comment by slayerjain** [comment]
Hi @Prasang023, the idea is to create a simple which would just run keploy test in GitHub actions. This obviously requires the application command to run, which could be extracted when the application is first recorded. You could probably set a default delay of something like 30 seconds.

**Comment by gouravkrosx** [comment]
@Prasang023 
Here is a sample GHA for your reference.
```yaml
name: Setup Application with Keploy

on: [push, pull_request]

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Set up your application
    # Add your application setup steps here
    - name: Setup Application
      run: |
        echo "Replace this line with your application setup commands"
        
    # Step 2: Install Keploy
    - name: Install Keploy
      run: |
        curl --silent --location "https://github.com/keploy/keploy/releases/latest/download/keploy_linux_amd64.tar.gz" | tar xz -C /tmp
        sudo mkdir -p /usr/local/bin && sudo mv /tmp/keploy /usr/local/bin/keploybin
        echo 'alias keploy="sudo -E env PATH=\"$PATH\" keploybin"' >> $GITHUB_ENV
        
    # Step 3: Test with Keploy
    - name: Test with Keploy
      run: |
        source $GITHUB_ENV
        keploy test -c "your application running command" --delay 30

```
