### ISSUE TITLE
[feature] : add docker command supoort

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#1505]
The GitHub action uses binary to run the GitHub Action due to which `docker command` can't be used to run the application with keploy.

```yml
- name: Keploy Report
      uses: keploy/testgpt@main
      with:
        working-directory: ./
        delay: 10
        command: docker compose up
        keploy-path: ./
```
the above config results to error below: -

![image](https://github.com/keploy/keploy/assets/53110238/dcdd3707-6c85-47ff-aa26-acf8ceba56c8)
