### ISSUE TITLE
[bug]: postgres breaking in test mode in case of client request streaming 

### ISSUE THREAD

**Issue by Sarthak160** [keploy/keploy#1788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

postgres parser is breaking in test mode when there is case of client request streaming .
for eg - 
```yaml
version: api.keploy.io/v1beta1
kind: Postgres
name: mock-3
spec:
    metadata:
        type: config
    postgresrequests:
        - header: [P]
          identifier: ClientRequest
          length: 62
          parse:
            - name: ""
              query: INSERT INTO users (name, email) VALUES ($1, $2) RETURNING *
              parameter_oids: []
          msg_type: 80
          auth_type: 0
        - header: [B]
          identifier: ClientRequest
          length: 62
          bind:
            - parameter_format_codes: [0, 0]
              parameters: [[74, 97, 110, 101, 32, 68, 111, 101], [106, 97, 110, 101, 64, 101, 120, 97, 109, 112, 108, 101, 46, 99, 111, 109]]
          msg_type: 66
          auth_type: 0
        - header: [D]
          identifier: ClientRequest
          length: 62
          describe:
            object_type: 80
            name: ""
          msg_type: 68
          auth_type: 0
        - header: [E]
          identifier: ClientRequest
          length: 62
          execute:
            - {}
          msg_type: 69
          auth_type: 0
```

### Steps to reproduce

1. Take any node application using pg pool client.
2. Make any api calls to create tests and mocks
3. Mostly streaming is done in case of insert call.
4. Run it on test mode it will give errors like - 
```
node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: Connection terminated unexpectedly
    at Connection.<anonymous> (/home/vamsee/shipsy/keploy/docker-compose-example/node_modules/pg/lib/client.js:132:73)
    at Object.onceWrapper (node:events:631:28)
    at Connection.emit (node:events:517:28)
    at Socket.<anonymous> (/home/vamsee/shipsy/keploy/docker-compose-example/node_modules/pg/lib/connection.js:62:12)
    at Socket.emit (node:events:517:28)
    at TCP.<anonymous> (node:net:350:12)
Emitted 'error' event on Client instance at:
    at Client._handleErrorEvent (/home/vamsee/shipsy/keploy/docker-compose-example/node_modules/pg/lib/client.js:332:10)
    at Connection.<anonymous> (/home/vamsee/shipsy/keploy/docker-compose-example/node_modules/pg/lib/client.js:150:16)
    at Object.onceWrapper (node:events:631:28)
    [... lines matching original stack trace ...]
    at TCP.<anonymous> (node:net:350:12)
   ```

### Environment

None

### Version

Cloud

### Repository

keploy
