### ISSUE TITLE
[bug]: keploy config breaks incase if a key includes dot in name in global noise

### ISSUE THREAD

**Issue by shivamsouravjha** [keploy/keploy#1910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

* While running something like the below code I get the error that `failed to unmarshal the config` 
```
test:
    selectedTests: {}
    globalNoise:
        global: 
          body:
            data.signIn.token: []
            data.signUp.token: []
```

### Steps to reproduce

🐰 Keploy: 2024-05-29T13:45:22+05:30    ERROR   failed to unmarshal the config  {"error": "1 error(s) decoding:\n\n* 'test.globalNoise.global[body][data][0]' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[sign:[ag]]'"}

This happens in release as the release build is released without tag of viper struct.
