### ISSUE TITLE
[feature]: exports tests as programmatic test files (go/js/other..)

### ISSUE THREAD

**Issue by Swpn0neel** [keploy/keploy#2026]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

It would be really helpful if keploy can also export tests into programmatic files. For eg: it could be test files written in go or js.

### Why should this be worked on?

While exporting to json/yaml is useful, they are not as useful or customizable as programmatic code like go/js. It could for example enable more powerful custom assertions and integrations.

### Repository

keploy

**Comment by vaishnavi192** [comment]
I would like to collaborate on this issue @Swpn0neel

**Comment by Swpn0neel** [comment]
> @Swpn0neel sir, could you please guide that is it like the test files which are created by Keply need to be converted into test files in Js or Go etc... like `fileName.spec.js`, something like that?

Currently, the test cases are mainly generated in yaml files in most cases, or in json format. But, based on the tech stack, we would like to generate it in that specific language, so that it becomes easier for us to execute them directly!

**Comment by vaishnavi192** [comment]
@Swpn0neel sure we will start working on it. @yaten2302 let's connect on slack.

**Comment by yaten2302** [comment]
@vaishnavi192 definitely 👍 can you share you slack id, so that we can connect over there?

**Comment by slayerjain** [comment]
I think a good starting point here could be creating go files. eg: `test-1.go` as an alternative to yaml files, eg:  `test-1.yaml`.  This will make it easy for devs to write assetions in pure golang and also leverage libraries.

**Comment by slayerjain** [comment]
What do you folks think could be a good golang representation of the test yaml files? :)

**Comment by yaten2302** [comment]
@slayerjain sir, actually, I was also thinking of this, but I've a doubt. I was reading about the test cases generated in yaml files [here](https://keploy.io/docs/quickstart/samples-nextjs/). In here, this is a sample api call made:
```json
{
  "users": [
    {
      "id": 3,
      "name": "John",
      "email": "doe@example.com",
      "createdAt": "2024-03-27T10:07:30.172Z"
    }
  ]
}
```
So, in test cases generated in YAML, somewhat this type of response will be generated:
```yaml
test_cases:
  - name: "Get User Data"
    request:
      method: GET
      url: http://localhost:3000/api/users
    response:
      status_code: 200
      body:
        name: "John"
        email: "doe@example.com"
    assertions:
      - assert_equal:
          actual: $.name
          expected: "John"
      - assert_equal:
          actual: $.email
          expected: "doe@example.com"
```
Now, we need to convert this into golang test case, which will look somewhat like this:
```go
package main

import (
    "encoding/json"
    "io/ioutil"
    "net/http"
    "testing"
)

type User struct {
    Name  string `json:"name"`
    Email string `json:"email"`
}

func TestGetUserData(t *testing.T) {
    resp, err := http.Get("http://localhost:3000/api/users")
    if err != nil {
        t.Fatalf("failed to make GET request: %v", err)
    }
    defer resp.Body.Close()

    if resp.StatusCode != http.StatusOK {
        t.Fatalf("expected status code 200 but got %d", resp.StatusCode)
    }

    body, err := ioutil.ReadAll(resp.Body)
    if err != nil {
        t.Fatalf("failed to read response body: %v", err)
    }

    var user User
    err = json.Unmarshal(body, &user)
    if err != nil {
        t.Fatalf("failed to unmarshal JSON: %v", err)
    }

    expectedUser := User{
        Name:  "John",
        Email: "doe@example.com",
    }

    if user != expectedUser {
        t.Errorf("expected user %+v but got %+v", expectedUser, user)
    }
}
```
Am I correct?
