### ISSUE TITLE
feat: Allow setting nested config options like filters and bypassRules via CLI flags

### ISSUE THREAD

**Issue by gouravkrosx** [keploy/keploy#2767]
## Description:
Currently, options like record.filters and bypassRules can only be set via the keploy.yml file. There’s no way to pass these values directly through CLI flags, which limits flexibility for users who prefer not to use a config file.

Example from config:

```yaml
record:
  filters:
    - path: "/health"
    - path: "/api/v2/apmtelemetry"

bypassRules:
  - path: "/health"

```

Desired CLI usage (not currently supported):
```bash
keploy record -c "./echo" --record.filters='[{"path":"/health"}]' --bypassRules='[{"path":"/health"}]'
```
