### ISSUE TITLE
Bug: Noise filtering fails for arrays of JSON objects

### ISSUE THREAD

**Issue by gouravkrosx** [keploy/keploy#2816]
## Description:
Keploy fails to filter noisy fields when the response body is an array of JSON objects or even an array of arrays containing JSON objects.

### Example:
```json
[
  {"id":1,"name":"Alice","created_at":"2025-06-26T17:38:54+05:30"},
  {"id":2,"name":"Bob","created_at":"2025-06-26T17:38:54+05:30"},
  {"id":3,"name":"Charlie","created_at":"2025-06-26T17:38:54+05:30"}
]

```
When the field `created_at` is marked as noisy in the global config or test-set noise section like below, Keploy does not filter it.

```yaml

test:
    selectedTests: {}
    globalNoise:
        global: {
            body: {
                "created_at",
            }
        }
        test-sets: {}
```
