### ISSUE TITLE
feat: Add Support for Secret Management via secret.yaml Configuration

### ISSUE THREAD

**Issue by gouravkrosx** [keploy/keploy#2822]
## Description:
Currently, Keploy uses `config.yaml` for storing templatized fields and values. We need to add support for a separate `secret.yaml` file to handle sensitive data, keeping secrets separate from regular configuration.

**Proposed Solution:**
1. Introduce a new `secret.yaml` file that:
   - Resides in the same directory as `config.yaml`
   - Follows the same structure as `config.yaml` but for sensitive values
   - Is explicitly excluded from version control via `.gitignore` by default
2. Modify the template syntax to support secret references:
   ```yaml
   # Regular config
   Accept: '{{string .Accept}}'
   
   # Secret reference
   Authorization: '{{string .secret.AuthToken}}'
   ```

**Security Considerations:**
- Secrets should never be logged or exposed in error messages

**Backward Compatibility:**
- Existing templates without `.secret.` prefix will continue to work as before
- Secret references will only be resolved if secret.yaml exists
