### ISSUE TITLE
[feature]: Add comments in keploy yamls to make better editable experience 

### ISSUE THREAD

**Issue by Sarthak160** [keploy/keploy#886]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

- Should add comments describing the fields of yaml and can also label to those mocks or fields which are not editable or can throw an error when omitted . Since in mocks as well some fields are important and can't be edited as now mock data comprises of the wire protocol attributes of a tcp buffer . 

- In order to that , adding a comment which informs user about edit can do the needful . 
 eg - 
 ```
# User Information
user:
  # Non-editable: The username is automatically generated.
  username: autogenerated_user

  # Editable: You can change the user's full name.
  full_name: John Doe
 ```

- Can also add an autogenerated comment above , which can be similar to code generated by libraries like gqlgen,go -grpc  etc . 
 eg - 
 ```
 # ---------------------------------------------------------------------------
# Keploy E2E Test Script
# Generated by Keploy
#

```

### Why should this be worked on?

This should be worked as it provides user the ability to change the test and mock data without causing any breaking change to it's application . 
This will improve the purpose of having editable tests and mocks . As labels of editable would be added after doing deep research about the readable mocks supported by keploy eg - mongo, postgres , HTTP , GRPC etc .

### Repository

keploy
